<?php 
session_start();
session_cache_expire(30);
include_once("database/dbSubmissions.php");
include_once("domain/Submission.php");

?>
<!--  page generated by the BowdoinRMH software package -->
<html>
    <head>
        <title>
        Approved Submissions
        </title>
        <!--  Choose a style sheet -->
        <link rel="stylesheet" href="styles.css" type="text/css"/>
        <!--<link rel="stylesheet" href="calendar.css" type="text/css"/> -->
        <!--    <link rel="stylesheet" href="calendar_newGUI.css" type="text/css"/> -->
    </head>
    <!--  Body portion starts here -->
    <body>
    <div id="container">
    <?PHP //include('header.php'); ?>
		<?php
			include('header.php');
			echo '
            <div class="topnav">
            <a href="' . $path . 'index.php">Home</a>
            <a href="' . $path . 'adminNewSubmission.php">Make New Submission</a>
            <a class = "active" href="' . $path . 'adminViewSubs.php">View Accepted Submissions</a>
            <a href="' . $path . 'viewNewSubs.php">View New Submissions</a>
            <a href="' . $path . 'emailList.php">Generate Emailing List</a>
            <a href="' . $path . 'createAdminAccount.php">Create Admin Account</a>
            <div class="topnav-right">
            <a href="' . $path . 'logout.php">Logout</a><br>
            </div>
            </div>';
			echo "<div id='content'>";
			echo "<center><h1>Approved Submissions</h1>";
			//echo "<br><center><form action='index.php' method='get'>
			//<input type='submit' value='Back to Homepage'></form>";
			$approvedSubs = retrieve_approved_submissions();
			
			for ($i = 0; $i < count($approvedSubs); $i++){
				//echo "<br><table style width='800'>";
				$id = $approvedSubs[$i]->get_id();
				$name = $approvedSubs[$i]->get_pet_name();
				$adopter = $approvedSubs[$i]->get_first_name()." ".$approvedSubs[$i]->get_last_name();
				$type = $approvedSubs[$i]->get_pet_type();
				
				$image = $approvedSubs[$i]->get_image();
				$image_src = "pictures/".$image;
				echo "<br><table style width='400'>";
				echo "<tr><td><img src=".$image_src." width='400' height='300'></td></tr>";
				echo "<tr><td><center><p style='font-size:25px;margin-bottom:0;'><b>".$name."</b></p>";
				echo "<br>Adopted by ".$adopter."</td></tr></table><br>";	

				echo "<form action='viewSubmission.php' method='post'>
				<input type='hidden' value='".$id."' name='id'>
				<input type='submit' value='View Adoption Story'>
				</form><br>";
			}
			echo "<br>";
		?>
    </div></div>
                    <?PHP include('footer2.inc'); ?>
    </body>
</html>

