
<?php
session_start();
session_cache_expire(30);
include_once("database/dbSubmissions.php");
include_once("domain/Submission.php");

?>
<!--  page generated by the BowdoinRMH software package -->
<html>
    <head>
	<script>
	function clicked(e) 
	{
	    if (!confirm('Are you sure you want to edit this submission?')) {
		e.preventDefault();
	    }
	}
        </script>
        <title>Submission</title>
        <!--  Choose a style sheet -->
        <link rel="stylesheet" href="styles.css" type="text/css"/>
        <link rel="stylesheet" href="calendar.css" type="text/css"/>
        <!--    <link rel="stylesheet" href="calendar_newGUI.css" type="text/css"/> -->
    </head>
    <!--  Body portion starts here -->
    <body>
    <div id="container">
	<?php
		include('header.php');
		echo "<div id='content'>";
		$email = $_POST['email'];
		$sub = retrieve_submission($email);

		echo "<center><h1>Edit Submission</h1>";	
		//display_submission($sub);
		$adopter = $sub->get_first_name()." ".$sub->get_last_name();
		$pet_name = $sub->get_pet_name();
		$pet_type = $sub->get_pet_type();
		$story = $sub->get_description();
		$image = $sub->get_image();
		$image_src = "pictures/".$image;
		echo "<table style width='500'><tr><td><img src=".$image_src." width='500' height='350'></td></tr>";
		echo "<tr><td><br><b>Pet Name:</b> ".$pet_name."</td></tr>";
		echo "<tr><td><b>Adopter:</b> ".$adopter."</td></tr>";
		echo "<form method='POST' action='verifySubmission.php'>";
		echo "<tr><td><b>Pet Type:</b> <input type='text' name='pet_type' value='".$pet_type."'></td></tr>";
		echo "<tr><td><b>Description:</b></td></tr>";
		echo "<tr><td><textarea name='description' rows='9' cols='65'>".$story."</textarea></td></tr></table><br><br>";
		echo "<input type='hidden' value='".$email."' name='email'>
		<input type='hidden' value='updated' name='updated'>
		<input type='submit' value='Save Changes' onclick='clicked(event)'></form><br><br><br>";
		echo "<form action='viewNewSubs.php' method='get'>
		<input type='submit' value='View Other Submissions'></form><br><br>";
	?>
    </div></div>
    <?php include('footer2.inc'); ?>
    </body>
</html>

