<?php 
session_start();
session_cache_expire(30);
include_once("database/dbSubmissions.php");
include_once("domain/Submission.php");

?>
<!--  page generated by the BowdoinRMH software package -->
<html>
    <head>
        <title>
            <?PHP echo('Generate Emailing List');?>
        </title>
        <link rel="stylesheet" href="lib/jquery-ui.css" />
        <link rel="stylesheet" href="styles.css" type="text/css" />
        <link rel="stylesheet" href="lib/jquery.timepicker.css" />
        <script src="lib/jquery-1.9.1.js"></script>
        <script src="lib/jquery-ui.js"></script>
        <script src="lib/jquery.timepicker.js"></script>
        <!--  Choose a style sheet -->
        <!--<link rel="stylesheet" href="styles.css" type="text/css"/>
        <link rel="stylesheet" href="calendar.css" type="text/css"/> -->
        <!--    <link rel="stylesheet" href="calendar_newGUI.css" type="text/css"/> -->
    </head>
    <!--  Body portion starts here -->
    <body>
    <div id="container">
    <?PHP include('header.php'); ?>
<?php
			//include('header.php');
            echo "<center><h1>Emailing List</h1></center>";
?>
    </body>
</html>
