<?php 
session_start();
session_cache_expire(30);
//include_once("database/dbSubmissions.php");
include_once("database/dbAdopters.php");
include_once("domain/Adopter.php");
//include_once("domain/Submission.php");

?>
<!--  page generated by the BowdoinRMH software package -->
<html>
    <head>
        <title>
        Generate Email List
        </title>
        <link rel="stylesheet" href="lib/jquery-ui.css" />
        <link rel="stylesheet" href="styles.css" type="text/css" />
        <link rel="stylesheet" href="lib/jquery.timepicker.css" />
        <script src="lib/jquery-1.9.1.js"></script>
        <script src="lib/jquery-ui.js"></script>
        <script src="lib/jquery.timepicker.js"></script>
        <!--  Choose a style sheet -->
        <!--<link rel="stylesheet" href="styles.css" type="text/css"/>
        <link rel="stylesheet" href="calendar.css" type="text/css"/> -->
        <!--    <link rel="stylesheet" href="calendar_newGUI.css" type="text/css"/> -->
    </head>
    <!--  Body portion starts here -->
    <body>
    <div id="container">
    <?PHP include('header.php'); 
			echo '
            <div class="topnav">
            <a href="' . $path . 'index.php">Home</a>
            <a href="' . $path . 'adminNewSubmission.php">Make New Submission</a>
            <a href="' . $path . 'adminViewSubs.php">View Accepted Submissions</a>
            <a href="' . $path . 'viewNewSubs.php">View New Submissions</a>
            <a class = "active" href="' . $path . 'emailList.php">Generate Emailing List</a>
            <a href="' . $path . 'createAdminAccount.php">Create Admin Account</a>
            <div class="topnav-right">
            <a href="' . $path . 'logout.php">Logout</a><br>
            </div>
            </div>';
    ?>
            <div id="content">
<?php 
            echo "<center><h1>Emailing List</h1></center>";
            //display the emails
            //get the subs
	    $adopters = retrieve_optin();
	    echo "<center/><br><table style width='500' border='2'>";
	    echo "<tr><td style='padding:8px'><p style='font-size':32px;margin-bottom:1;'><b>Adopter Name</b></p></td><td><p style='font-size':32px;margin-bottom:1;'><b>Email Address</b></p></td></tr>";
            for($i = 0; $i < count($adopters); $i++) {
                $name = $adopters[$i]->get_first_name()." ".$adopters[$i]->get_last_name();
                $email = $adopters[$i]->get_email();
                //echo "<center/><br><table style width='500' border='2'>";
                echo"<center/><tr><td style='padding:8px'><p style='font-size':30px;margin-bottom:1;'>".$name."</p></td><td><p style='font-size':30px;margin-bottom:1;'>".$email."</p></td></tr>";
	    }
	    echo "</table>";
?>
    </div>
    </div>
                    <?PHP include('footer2.inc'); ?>
    </body>
</html>
