<!-- Begin Footer -->
<br /><br />
<div class="sfooter">
<table style="color: white; font-size: 30px;">
<tr><td>
    <img src="fredspca.png" alt="SPCA Logo"></td><td>                 </td>
    <td><center/>&copy Copyright 2021 - Fredericksburg SPCA | Powered by Metro Nova Creative Solutions</td>
</tr></table>
</div>

<style>
.sfooter {
	padding: 20px;
	text-align: center;
	background: #00488A;
	color: white;
	font-size: 30px;
	left: 0;
	right: 0;
	top: 0;	
}
</style>
<!-- End Footer -->
