<!-- Begin Footer -->
<br /><br />
<div class="sfooter">
<table style="color: white; font-size: 30px;">
<tr><td>
    <img src="fredspca.png" alt="SPCA Logo"></td><td>                 </td>
    <td style="font-size: 20px; padding-left:50px;"><center/>&copy Copyright 2021 - Fredericksburg SPCA | Powered by Metro Nova Creative Solutions</td>
</tr></table>
</div>

<style>
.sfooter {
	padding: 20px 20px;
	text-align: center;
	background: #00488A;
	color: white;
	font-size: 90px;
	left: 0;
	right: 0;
	bottom: 0;
	position: absolute;
	overflow: hidden;
}
</style>
<!-- End Footer -->
