<?php 
include_once("database/dbSubmissions.php");
include_once("domain/Submission.php");

?>
<!--  page generated by the BowdoinRMH software package -->
<html>
    <head>
        <title>Submission</title>
        <!--  Choose a style sheet -->
        <!--<link rel="stylesheet" href="styles.css" type="text/css"/>
        <link rel="stylesheet" href="calendar.css" type="text/css"/>-->
        <!--    <link rel="stylesheet" href="calendar_newGUI.css" type="text/css"/> -->
    </head>
    <!--  Body portion starts here -->
    <body>
	<?php
		include('header2.php');
		$email = $_POST['email'];
		$sub = retrieve_submission($email);

		echo "<center><h1>New Submission</h1>";	
		//display_submission($sub);
		$adopter = $sub->get_first_name()." ".$sub->get_last_name();
		$pet_name = $sub->get_pet_name();
		$pet_type = $sub->get_pet_type();
		$story = $sub->get_description();
		$image = $sub->get_image();
		$image_src = "pictures/".$image;
		echo "<table style width='500'><tr><td><img src=".$image_src." width='500' height='350'></td></tr>";
		echo "<tr><td><br><b>Pet Name:</b> ".$pet_name."</td></tr>";
		echo "<tr><td><b>Adopter:</b> ".$adopter."</td></tr>";
		echo "<tr><td><b>Pet Type:</b> ".$pet_type."</td></tr>";
		echo "<tr><td><b>Description:</b></td></tr>";
		echo "<tr><td>".$story."</td></tr></table><br><br>";

		echo "<form action='approveSub.php' method='get'>
		<input type='submit' value='Approve Submission'></form><br><br>";
		echo "<form action='viewNewSubs.php' method='get'>
		<input type='submit' value='View Other Submissions'></form><br><br>";
		echo "<form action='viewNewSubs.php' method='get'>
		<input type='submit' value='Edit Submission'></form><br><br>";
		echo "<form action='denySub.php' method='get'>
		<input type='submit' value='Deny Submission'></form><br><br>";
	?>
    </body>
</html>

