<?php 
include_once("database/dbSubmissions.php");
include_once("domain/Submission.php");

?>
<!--  page generated by the BowdoinRMH software package -->
<html>
    <head>
        <title>Accepted Submissions</title>
        <!--  Choose a style sheet -->
        <link rel="stylesheet" href="styles.css" type="text/css"/>
        <link rel="stylesheet" href="calendar.css" type="text/css"/>
        <!--    <link rel="stylesheet" href="calendar_newGUI.css" type="text/css"/> -->
    </head>
    <!--  Body portion starts here -->
    <body>
        <div id="container">
            <div id="content">
		<?php
			$approvedSubs = retrieve_approved_submissions();
			//display_submissions($approvedSubs);
			for ($i = 0; $i < count($approvedSubs); $i++){
				display_submission($approvedSubs[$i]);
				$image = $approvedSubs[$i]->get_image();
				$image_src = "pictures/".$image;
				echo "<img src=".$image_src."><br>";	
			}
		?>
            </div>
        </div>
    </body>
</html>

