<?php 
include_once("database/dbSubmissions.php");
include_once("domain/Submission.php");

?>
<!--  page generated by the BowdoinRMH software package -->
<html>
    <head>
        <title>Accepted Submissions</title>
        <!--  Choose a style sheet -->
        <link rel="stylesheet" href="styles.css" type="text/css"/>
        <link rel="stylesheet" href="calendar.css" type="text/css"/>
        <!--    <link rel="stylesheet" href="calendar_newGUI.css" type="text/css"/> -->
    </head>
    <!--  Body portion starts here -->
    <body>
        <div id="container">
            <div id="content">
		<?php
			//$sub = retrieve_submission("w");
			$approvedSubs = retrieve_unapproved_submissions();
                    	display_submissions($approvedSubs);
                ?>
            </div>
        </div>
    </body>
</html>

